### ISSUE TITLE
Invocation?

### ISSUE THREAD

**Issue by gmcmicken** [jeremeamia/slack-app-framework#1]
Hey nice work on this, I went to try it out but I'm a bit confused about how this is invoked by slack? Is it supposed to be a catch all for the events API?

**Comment by jeremeamia** [comment]
@gmcmicken Hey, thanks for checking this out. I'm still in the middle of some heavy development on this package, and am not even at an alpha release yet, so keep that in mind.

This is meant to be a framework for developing any kind of Slack apps, based on their development platform. It can listen to events (from the events API), but allows for handling any other kind of interaction (e.g., slash commands; button clicks; opening, submitting, and closing modals; shortcuts; etc.). It is in the same vein as [Slack's "Bolt" framework](https://slack.dev/bolt-js) for JavaScript. To learn more about Slack app development in general, there is quite a bit of reading to do: https://api.slack.com/start/overview.

When you setup an app in Slack, you configure the URLs it uses to handle events, commands, interactions, and shortcuts. You can point those URLs in your app configuration to whatever you build and deploy with this framework (or Bolt).

_Related:_ I also have another library (https://github.com/jeremeamia/slack-block-kit), which is more stable, and is used to help format Block Kit messages/modals. This framework uses slack-block-kit in a several places, as well as https://github.com/jolicode/slack-php-api, which is a Slack API client. So depending on what you need, those two standalone packages might be helpful too.

**Comment by gmcmicken** [comment]
Thanks yea I have a base familiarity with slack's API but still I'm wondering about the correlation of webhook/url to this package. In your example you have a bunch of different things being defined (command, globalShortcut, event, etc) at the same time, so is this to say for your example I would perhaps configure event URL, and slash command URL to the same location? There's no additional routing required?

**Comment by jeremeamia** [comment]
> for your example I would perhaps configure event URL, and slash command URL to the same location

Yes, so in your app configuration could configure the URL to your code (I have one hosted in AWS at the moment)
![Screen Shot 2021-03-04 at 3 30 08 PM](https://user-images.githubusercontent.com/107867/110040473-20e0af80-7d00-11eb-98c1-fe2ae699cace.png)
And you would set the same URL for your Slack Commands and Event Subscriptions.

The routing in the app is done by processing the incoming payload from Slack, and looking at the `type` field (e.g., `command`, `shortcut`, `event_callback`, etc.) and a corresponding type-specific name/ID value you've configured.

#### Example
If you configured a message shortcut called "Foo Bar" with a Callback ID of "foo_bar" to point to your code's URL, when a user uses the shortcut, a request will come into the framework (after it is parsed and normalized) looking something like this:
```json
{
  "type": "message_action",
  "token": "<redacted>",
  "action_ts": "1614898125.086327",
  "callback_id": "foo_bar",
  "response_url": "https://hooks.slack.com/app/T01BR0BGSMQ/1824800600355/Lap825hKzw1Qqe1FjKyt7Kbv",
  ...
  "message_ts": "1614898117.000200",
  "message": {
    "type": "message",
    "text": "foo",
    "user": "U<redacted>K",
    "ts": "1614898117.000200",
    ...
  }
}
```
In this case the `type` and `callback_id` are used for routing, so in your code you can so something like:
```php
App::new()
    ->messageShortcut('foo_bar', function (Context $ctx) {
        $message = $ctx->payload()->get('message.text');
        $ctx->respond("The message you used the shortcut on said: {$message}");
    })
    ->run();
```

**Comment by gmcmicken** [comment]
Awesome, I should have just tried it (actually I did just before your comment) and it works great. Really simple to use. Good work.

**Comment by jeremeamia** [comment]
Awesome. Thanks for diving in and taking a look. I'll be working on getting everything tied up for an initial release this month.

**Comment by jeremeamia** [comment]
I've updated the README with some information that would have addressed your questions. I also opened up the "Discussions" board for the repo, so if you have any questions in the future, let me know.

**Comment by gmcmicken** [comment]
Much appreciated, thanks!
